/*
 * FTS API
 *
 * This is FTS(Funds Transfer Service) server API document.
 *
 * API version: 1.0
 * Contact: dickrj@163.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UtilsHttpError struct {
	Code    int32  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
