/*
 * FTS API
 *
 * This is FTS(Funds Transfer Service) server API document.
 *
 * API version: 1.0
 * Contact: dickrj@163.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "time"

type AccountAccount struct {
	ID        uint       `json:"ID,omitempty"`
	CreatedAt time.Time  `json:"CreatedAt,omitempty"`
	UpdatedAt time.Time  `json:"UpdatedAt,omitempty"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	Balance   int32      `json:"balance,omitempty"`
	Email     string     `json:"email,omitempty"`
	Password  string     `json:"password,omitempty"`
	Phone     string     `json:"phone,omitempty"`
	Username  string     `json:"username,omitempty"`
}
