/*
 * FTS API
 *
 * This is FTS(Funds Transfer Service) server API document.
 *
 * API version: 1.0
 * Contact: dickrj@163.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountLoginRsp struct {
	Name  string `json:"name,omitempty"`
	Token string `json:"token,omitempty"`
}
