apiVersion: v1
kind: Service
metadata:
  name: fts
  labels:
    app: fts
spec:
  type: NodePort
  selector:
      app: fts
  ports:
  - protocol : TCP
    nodePort: 30808
    port: 8080
    targetPort: 8080 