apiVersion: apps/v1
kind: Deployment 
metadata:
  name: prometheus
  labels:
      app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: quay.io/prometheus/prometheus:latest
          name: prometheus
          imagePullPolicy: Never
          ports:
            - containerPort: 9090 
              name: prometheus 